//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebay.FishbowlIntegration.SQL {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FB {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FB() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ebay.FishbowlIntegration.SQL.FB", typeof(FB).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FB_CountryAndState {
            get {
                return ResourceManager.GetString("FB_CountryAndState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select first 1 
        ///    customer.name 
        ///from CONTACT     
        ///    join customer on customer.accountid = contact.ACCOUNTID 
        ///where contact.DATUS = @eml
        ///and contact.typeid = 60 /*Email*/.
        /// </summary>
        internal static string FB_FindCustomerByEmail {
            get {
                return ResourceManager.GetString("FB_FindCustomerByEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from (
        ///
        ///select product.num, COALESCE( IIF( SUM(QTYINVENTORYTOTALS.QTYONHAND) - SUM(QTYINVENTORYTOTALS.QTYALLOCATED) &lt; 0, 0, SUM(QTYINVENTORYTOTALS.QTYONHAND) - SUM(QTYINVENTORYTOTALS.QTYALLOCATED) ) ,0) as QTY
        ///from PART
        ///    join product on product.partid = part.id
        ///    left join QTYINVENTORYTOTALS on QTYINVENTORYTOTALS.PARTID = part.id
        ///where part.typeid = 10 
        ///group by 1 
        ///
        ///union all
        ///
        ///select product.num, MIN ( COALESCE( (select SUM(tag.qty)-SUM(tag.QTYCOMMITTED) from tag where partid = kp.p [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FB_GetInventory {
            get {
                return ResourceManager.GetString("FB_GetInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FB_GetProductPrice {
            get {
                return ResourceManager.GetString("FB_GetProductPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select
        ///
        ///product.num,
        ///0 as QTY,
        ///product.price,
        ///product.weight
        ///
        ///from product
        ///.
        /// </summary>
        internal static string FB_GetProductWeight {
            get {
                return ResourceManager.GetString("FB_GetProductWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select
        ///
        ///product.num,
        ///CAST(0 as double precision) as qty,
        ///product.price,
        ///product.weight
        ///
        ///from product.
        /// </summary>
        internal static string FB_ProductPriceWeight {
            get {
                return ResourceManager.GetString("FB_ProductPriceWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///ship.num SNUM,
        ///so.CUSTOMERPO as CPO,
        ///LIST(distinct shipcarton.TRACKINGNUM) as TRACKINGNUM
        ///
        ///from SHIP
        ///    join so on so.id = ship.SOID
        ///    join shipcarton on shipcarton.shipid = ship.ID
        ///where ship.DATESHIPPED &gt; @dte  
        ///group by 1,2    .
        /// </summary>
        internal static string FB_ShipmentsToUpdate {
            get {
                return ResourceManager.GetString("FB_ShipmentsToUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string test_file_txt {
            get {
                return ResourceManager.GetString("test_file.txt", resourceCulture);
            }
        }
    }
}
